# This is a basic workflow to help you get started with Actions

name: Trial

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      web:
        image: nginx
        ports:
          - 80:80
    steps:
    - uses: actions/checkout@v2
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      with:
        install: true
    - name: building image
      env:
        DB: localhost
      run: |
        docker build --network=host --build-arg DB=localhost -t .
