# This is a basic workflow to help you get started with Actions

name: Trial

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      web:
        image: python:3.7
        tty: true
        stdin_open: true
        ports:
          - 8080:8080
    steps:
    - uses: actions/checkout@v2
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      with:
        install: true
    - name: building image
      env:
        DB: localhost
      run: |
        docker build --net=host --build-arg DB=$DB -t .
